name: NexusChatLevels
version: '2.0'
main: me.kythera.chatLevels.ChatLevels
api-version: '1.21'
authors: [ Kythera ]
description: NexusChatLevels by Kythera.
softdepend: ["PlaceholderAPI"]

commands:
  chatlvls:
    description: Allows players to use Chat Levels.
    usage: /chatlevels <parameters>
    permission: chatlevels.use

permissions:
  chatlevels.use:
    default: true
    description: Allows players to use chatlevels
  chatlevels.admin:
    default: op
    description: Allows players to use admin permissions in chatlevels